### ISSUE TITLE
ReShade 6.3.0 incompatible with CubeLUT3D.fx

### ISSUE THREAD

**Issue by HqT65W6R** [liuxd17thu/BX-Shade#1]
My LUT for CubeLUT3D.fx works fine with ReShade 6.2.0, but shows all kinds of artifacts in 6.3.0. I think shader needs an update to be compatible with ReShade 6.3.0.

**Comment by liuxd17thu** [comment]
That's an issue inside ReShade program and I have raised a PR to crosire: https://github.com/crosire/reshade/pull/327
You can downgrade to 6.2.0 and wait for a hotfix.

**Comment by liuxd17thu** [comment]
Fixed in ReShade 6.3.1
